
dubbo:
  application:
    name: user-service
  registry:
    protocol: zookeeper
    address: 192.168.244.201:2181 #dubbo注册中心zookeeper地址
  protocol:
    name: dubbo
  scan:
    base-packages: com.iflytek.gmall
  consumer:
    timeout: 6000
    check: false












